# Generated by Django 2.1.5 on 2019-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_message',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'new_message',
            },
        ),
    ]
