#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-03-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSay',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('classSayName', models.CharField(max_length=20)),
                ('classSayContent', models.CharField(max_length=200)),
                ('classSayImage', models.ImageField(upload_to='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ClassSay',
            },
        ),
    ]
