#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-03-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0005_auto_20190329_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('studentName', models.CharField(max_length=20)),
                ('studentContent', models.CharField(max_length=1000)),
                ('studentImage', models.ImageField(upload_to='./static/files/classSay')),
                ('studentMoney', models.IntegerField()),
                ('studentCompany', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'studentMessage',
            },
        ),
    ]
