#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0006_studentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='studentSex',
            field=models.IntegerField(default=1),
        ),
    ]
