#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-03-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0007_studentmessage_studentsex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
