#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-04-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0008_auto_20190330_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=20)),
                ('teacherTitle', models.CharField(max_length=20)),
                ('teacherLabel', models.CharField(max_length=20)),
                ('teacherContent', models.CharField(max_length=400)),
                ('teacherImage', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'teacherMessage',
            },
        ),
    ]
