#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-04-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0010_auto_20190403_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermessage',
            options={'verbose_name_plural': '老师信息'},
        ),
    ]
