# Generated by Django 2.1.5 on 2019-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0011_auto_20190403_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermessage',
            name='teacherImage',
            field=models.ImageField(upload_to='./static/files/classSay', verbose_name='老师图片'),
        ),
        migrations.AlterModelTable(
            name='classsay',
            table='课程介绍',
        ),
        migrations.AlterModelTable(
            name='new_message',
            table='最新消息',
        ),
        migrations.AlterModelTable(
            name='studentmessage',
            table='学生信息',
        ),
        migrations.AlterModelTable(
            name='trickmessage',
            table='就业信息',
        ),
    ]
