#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0013_auto_20190406_1207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trickmessage',
            table='trickMessage',
        ),
    ]
