#!/usr/bin/python3
# @File:.py
# -*- coding:utf-8 -*-
# @Author:von_fan
# Generated by Django 2.1.5 on 2019-04-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0014_auto_20190406_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='权重（按从大到小排列）')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'db_table': 'Classification',
                'verbose_name_plural': '视频分类',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='权重(按从大到小排列)')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classification', models.ManyToManyField(to='websiteBefore.Classification')),
            ],
            options={
                'db_table': 'Direction',
                'verbose_name_plural': '方向（视频方向）',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='难度')),
            ],
            options={
                'db_table': 'Level',
                'verbose_name_plural': '学习难度',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(verbose_name='权重（按从大到小排列）')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简介')),
                ('img', models.ImageField(upload_to='./static/files/Video', verbose_name='图片')),
                ('href', models.CharField(max_length=32, verbose_name='视频地址')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='websiteBefore.Classification')),
                ('level', models.ForeignKey(on_delete='CASCADE', to='websiteBefore.Level')),
            ],
            options={
                'db_table': 'Video',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AlterModelOptions(
            name='trickmessage',
            options={'verbose_name_plural': '就业信息'},
        ),
    ]
