# Generated by Django 2.1.5 on 2019-04-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteBefore', '0015_auto_20190409_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='href',
            field=models.CharField(max_length=1000, verbose_name='视频地址'),
        ),
    ]
